SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ='${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}'
SOCIAL_AUTH_GITHUB_KEY = '${SOCIAL_AUTH_GITHUB_KEY}'
SOCIAL_AUTH_GITHUB_SECRET = '${SOCIAL_AUTH_GITHUB_SECRET}'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '${SECRET_KEY}'

ALLOWED_HOSTS = ${ALLOWED_HOSTS}

