language: python

python:
  - 3.7

branches:
  only:
    - shippable

script:
  - env | sort

#resources:
#  - name:           gae_int
#    type:           integration
#    integration:    https://app.shippable.com/subs/github/pratclot/integrations
jobs:
  - name:           gae_job
    type:           runSh
    steps:
#      - IN:         gae_int
      - TASK:
        - script:   env | sort
        - script:   shipctl copy_file_from_prev_state "config.json" .
        - script:   shippable/deploy.sh

